if("${CMAKE_GENERATOR_PLATFORM}" MATCHES "x64")
	set(VTK8.2_DIR ${CMAKE_CURRENT_LIST_DIR}/VTK/VTK8.2/x64/lib/cmake/vtk-8.2)

	set(ITK5.1_DIR ${CMAKE_CURRENT_LIST_DIR}/ITK/ITK5.1/x64/lib/cmake/ITK-5.1)
	set(ITK5.2_DIR ${CMAKE_CURRENT_LIST_DIR}/ITK/ITK5.2/x64/lib/cmake/ITK-5.2)
endif()